# Generated by Django 3.1 on 2022-05-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('tipo_cuenta', models.CharField(choices=[('INGRESOS', 'INGRESOS'), ('GASTOS', 'GASTOS'), ('AMBOS', 'AMBOS')], max_length=64)),
                ('permite_cuotas', models.BooleanField(default=False)),
            ],
        ),
    ]
